jobs:
  build:
    working_directory: ~/balalaika_bear
    docker:
      - image: elixir:latest

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
            - v1-dependency-cache-{{ arch }}
            - v1-dependency-cache

      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix credo
      - run: mix format --check-formatted
      - run:
          command: mix compile
          environment:
            MIX_ENV: test

      - save_cache:
          key: v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix

      - run: mix test